# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/5-Minute-Production-App.gitlab-ci.yml

# This template is on early stage of development.
# Use it with caution. For usage instruction please read
# https://gitlab.com/gitlab-org/5-minute-production-app/deploy-template/-/blob/v3.0.0/README.md


stages:
  - build
  - test
  - provision
  - deploy
  - destroy

raju:
  stage: build
  script:
    - echo "hello"
sai:
  stage : test
  script:
    - export IMAGE_NAME=ubuntuk8s/ubuntu-terraform:latest
    - docker build -t $IMAGE_NAME 
    - echo "done"
