stages:
  - build
  - test
  - deploy

image: ubuntu

build_a:
  stage: build
  script:
    - cd
    - ls
    - mkdir sai
    - cd sai/
    - touch sai.txt
    - pwd
    - echo "This job builds something." >> sai.txt
    -cat sai.txt
