stages:
  - build
  - test
  - deploy
  - prod
image: ubuntu

build_a:
  stage: build
  script:
    - apt update -y
    - apt search docker.io
    - apt install docker.io -y
    - systemctl enable docker
    - systemctl start docker
    - docker --version 
    - docker pull owasp/zap2docker-stable
    - docker images
    - docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained \ --start-options '-config api.disablekey=true' https://www.google.com
