stages:
  - build
  - test
  - deploy
  - prod
image: docker:git

build_a:
  stage: build
  services:
    - name: docker:19.03.8-dind

  script:
    - docker --version 
    - docker pull nginx:latest
    - docker images
    - docker run -i owasp/zap2docker-tests:latest zap-cli quick-scan --self-contained \ --start-options '-config api.disablekey=true' https://www.google.com
