stages:
  - build
  - test
  - deploy
  - prod
image: docker:git

build_a:
  stage: build
  services:
    - name: docker:19.03.8-dind

  script:
    - docker --version
    - docker images
    - docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://targethttps://www.google.com -quickout /path/to/report.xml

