stages:
  - build
  - test
  - deploy

image: ubuntu

build_a:
  stage: build
  script:
    - cd
    - ls
    - mkdir sai
    - cd sai/
    - touch sai.txt
    - pwd
    - echo "This job builds something." >> sai.txt
    - cat sai.txt
    - cd
    - RUN apt update
    - RUN apt install wget -y
    - wget https://releases.hashicorp.com/terraform/1.0.8/terraform_1.0.8_linux_amd64.zip
    - ls
    - unzip -p terraform_1.0.8_linux_amd64.zip
    - cp terraform /bin
    - terraform --version
