stages:
  - build
  - test
  - deploy
  - prod
image: ubuntu:latest

build_a:
  stage: build
  services:
    - name: ubuntu
  script:
    - ls
    - apt-get update
    - apt-get install docker.io
    - docker --version 


