stages:
  - build
  - test
  - deploy
  - prod
image: ubuntu:latest

build_a:
  stage: build
  services:
    - name: ubuntu
  script:
    - ls
    - apt-get update
    - apt-get install -y unzip
    - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
    - ls
    - unzip terraform_0.12.24_linux_amd64.zip
    - cd /terraform_0.12.24_linux_amd64
    - mv terraform /usr/local/bin
    - terraform --version


