stages:
  - build
  - test
  - deploy
  - prod
image: ubuntu:latest

build_a:
  stage: build
  services:
    - name: ubuntu
  script:
    - ls
    - apt-get update
    - apt-get install -y unzip
    - apt-get install -y wget
    - wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
    - ls
    - unzip terraform_0.12.24_linux_amd64.zip
    - ls
    - mv terraform /usr/local/bin
    - terraform --version
    - cd terraform-aws-elb-alb/
    - terraform init --backend-config="access_key=$AWS_ACCESS_KEY_ID" --backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
    - terraform validate -no-color
    - terraform plan -no-color
    - terraform apply --auto-approve -no-color
#    - terraform taint module.image_dev_content.null_resource.push
#    - terraform taint module.image_dev_frontend.null_resource.push
#    - terraform taint module.image_dev_masterdata.null_resource.push
#    - terraform taint module.image_dev_frontend_config.null_resource.push
#    - terraform taint module.image_dev_partner.null_resource.push
#    - terraform taint module.image_dev_user.null_resource.push
#    - terraform taint module.image_dev_events.null_resource.push



