stages:
  - build
  - test
  - deploy
  - prod
image: docker

build_a:
  stage: build
  script:
    - docker --version 
    - docker pull owasp/zap2docker-live
    - docker images
    - docker run -i owasp/zap2docker-live zap-cli quick-scan --self-contained \ --start-options '-config api.disablekey=true' https://www.google.com
